console.log("============================================================");
console.log("RC406-D55R40:");
console.log("LIVE COOPERATIVE ADMIN AUTH / REDIRECT CORRELATION PROBE");
console.log("============================================================");
console.log("");
console.log("DIAGNOSTIC ONLY — NO PRODUCTION PATCH APPLIED.");
console.log("");
console.log("Browser probe:");
console.log("");
console.log("(async () => {");
console.log("    console.log('===== RC406-D55R40 LIVE PROBE START =====');");
console.log("");
console.log("    try {");
console.log("        const firebaseModule = await import('./js/firebase-config.js');");
console.log("        const controller = await import('./js/controllers/accessController.js');");
console.log("");
console.log("        const auth = firebaseModule.auth;");
console.log("");
console.log("        console.log('R40 T0 current URL:', window.location.href);");
console.log("");
console.log("        console.log('R40 T1 auth.currentUser:', auth.currentUser ? {");
console.log("            uid: auth.currentUser.uid,");
console.log("            email: auth.currentUser.email,");
console.log("            emailVerified: auth.currentUser.emailVerified");
console.log("        } : null);");
console.log("");
console.log("        const unsubscribe = controller.watchAuthentication((user) => {");
console.log("            console.log('R40 T2 onAuthStateChanged:', user ? {");
console.log("                uid: user.uid,");
console.log("                email: user.email,");
console.log("                emailVerified: user.emailVerified");
console.log("            } : null);");
console.log("        });");
console.log("");
console.log("        console.log('R40 T3 auth listener installed');");
console.log("");
console.log("        const access = await controller.enforceDashboardAccess('cooperative_admin');");
console.log("");
console.log("        console.log('R40 T4 enforceDashboardAccess result:', access);");
console.log("");
console.log("        console.log('R40 T5 auth.currentUser after enforcement:', auth.currentUser ? {");
console.log("            uid: auth.currentUser.uid,");
console.log("            email: auth.currentUser.email,");
console.log("            emailVerified: auth.currentUser.emailVerified");
console.log("        } : null);");
console.log("");
console.log("        unsubscribe();");
console.log("");
console.log("        console.log('===== RC406-D55R40 LIVE PROBE COMPLETE =====');");
console.log("    } catch (error) {");
console.log("        console.error('===== RC406-D55R40 PROBE ERROR =====');");
console.log("        console.error(error);");
console.log("    }");
console.log("})();");
console.log("");
console.log("============================================================");
console.log("RC406-D55R40 SCRIPT VALIDATION COMPLETE");
console.log("============================================================");
